### ISSUE TITLE
Missing configuration for classpath grid

### ISSUE THREAD

**Issue by Ph3n1x** [excelsior-oss/excelsior-jet-gradle-plugin#13]
I am using the Bouncycastle library and therefore need to define the "Pack into exe" option with "as a whole".

This option is missing. At least I could not find it.

**Comment by pjBooms** [comment]
Hi! 

Thank you for your feedback!

The next release of the [plugin](https://github.com/excelsior-oss/excelsior-jet-gradle-plugin/tree/azhidkov/dependency-management#dependencies-management)  will add this functionality. We are going to release it on the next week (maybe earlier). Stay tuned!

**Comment by Ph3n1x** [comment]
Oh, great! I am looking forward to that! :)

**Comment by pjBooms** [comment]
0.8.0 version of the plugin has released that adds this capability. So you may try it now.

And thanks again for your Pull Request
