### ISSUE TITLE
jetTestRun Options

### ISSUE THREAD

**Issue by cheese-stands-alone** [excelsior-oss/excelsior-jet-gradle-plugin#33]
Have runTestRun read some of the properties set in gradle's excelsiorJet section, such as compilerOptions, stackTraceSupport, etc.

**Comment by pjBooms** [comment]
Sorry for long silence. 

During Test Run your application runs on Excelsior JET JVM in bytecode form, so all your classes are JITed during the Test Run 

compilerOptions, stackTraceSupport parameters are applicable only to AOT compiler.

On the other hand runArgs, jvmArgs affects directly the Test Run.
