### ISSUE TITLE
Project task path for nested multiprojects generate incorrect path

### ISSUE THREAD

**Issue by Crazyjavahacking** [excelsior-oss/excelsior-jet-gradle-plugin#37]
Currently `ExcelsiorJetPlugin.groovy` contains the following code:
```
private static String taskPath(Project target, String taskName) {
    if (target.rootProject == target) {
        return ":$taskName"
    } else {
        return ":${target.name}:$taskName"
    }
}
```
This is incorrect as when the project is part of the multiproject build with deeper hierarchies, this will generate invalid Gradle project path:

e.g. for project with path `:terminal:terminal-assembly` `taskpath` task will generate invalid path `:terminal-assembly:jar`

The code should use `org.gradle.api.Project.getPath()` functionality instead.

**Comment by pjBooms** [comment]
Fixed in 1.1.3 release
